Repository Nishitbaria/OpenGrame, pull requests merged in 2024-05, with the labels that each got.

#14 fixes: height overflow in register and login page
  src/_auth/AuthLayout.tsx
  src/_auth/forms/SignupForm.tsx
  src/globals.css
Labels: good first issue, gssoc, level1

#28 fix: Default followers and following count
  src/_auth/forms/SignupForm.tsx
  src/_root/pages/Profile.tsx
Labels: good first issue, level1

#35 feat:docker file
  .dockerignore
  Dockerfile
Labels: goal: new-feature, priority: high

#33 Feat: Added the search functionality on people page
  src/_root/pages/AllUsers.tsx
  src/lib/appwrite/api.ts
  src/lib/react-query/queriesAndMutations.ts
  src/lib/react-query/queryKeys.ts
Labels: gssoc, level3, goal: new-feature

#40 feat: Share profile feature (#34)
  package-lock.json
  package.json
  public/assets/icons/copy.svg
  src/_root/pages/Profile.tsx
  src/components/ui/dialog.tsx
Labels: gssoc, level3, goal: new-feature, priority: high

#44 [DOCS] Added Table of contents and featured in section to the readme file
  .github/assets/gssoc24.png
  .github/docs/gssoc.md
  README.md
Labels: documentation, gssoc, level1, goal: new-feature, priority: high

#53 feat: create a Share Post Feature
  package-lock.json
  package.json
  public/assets/icons/cancel.svg
  src/components/shared/PostStats.tsx
  src/components/ui/Share.tsx
Labels: gssoc, level3, goal: new-feature, priority: high, Request: Changes

#62 ✨feature: Logout Alerting screen #36
  package-lock.json
  package.json
  src/components/shared/LeftSidebar.tsx
  src/components/shared/Logout.tsx
  src/components/ui/alert-dialog.tsx
Labels: gssoc, level2, goal: new-feature, priority: high

#65 fix #54 personal profile display issue on People Search page
  src/_root/pages/AllUsers.tsx
Labels: bug, gssoc, level2, priority: medium

#72 fix: update bio rendering
  src/_root/pages/Profile.tsx
Labels: bug, gssoc, level1, goal: build, priority: medium

#83 Clarifies messages on Login and Signup pages
  package-lock.json
  src/_auth/forms/SigninForm.tsx
Labels: gssoc, level1

#93 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc, level1

#95 Fix the scrolling in signup form and added show password eye icon in both Sign up and Login form.
  package-lock.json
  src/_auth/forms/SigninForm.tsx
  src/_auth/forms/SignupForm.tsx
Labels: bug, gssoc, level2, priority: medium

#91 [Feature] - Custom 404 Not Found page added
  public/assets/images/bg.jpg
  public/assets/images/logo.png
  src/App.tsx
  src/_root/pages/Custom404.tsx
  tailwind.config.js
Labels: goal: new-feature, priority: high

#109 Update SigninForm.tsx
  src/_auth/forms/SigninForm.tsx
Labels: gssoc, level1

#86 Feat #74 : Create a Story Component
  .env.local_example
  appwrite.json
  package-lock.json
  public/assets/icons/stories.svg
  src/App.tsx
  src/_root/pages/CreateStory.tsx
  src/_root/pages/Home.tsx
  src/_root/pages/Saved.tsx
  src/components/forms/CreateStoryForm.tsx
  src/components/shared/LeftSidebar.tsx
  src/components/shared/Settings.tsx
  src/components/shared/StoriesContainer.tsx
  src/components/shared/StoryModel.tsx
  src/components/ui/Story.tsx
  src/components/ui/dialog.tsx
  src/constants/index.ts
  src/globals.css
  src/lib/appwrite/api.ts
  src/lib/appwrite/config.ts
  src/lib/react-query/queriesAndMutations.ts
  src/lib/react-query/queryKeys.ts
  src/lib/validation/index.ts
  src/types/index.ts
  tailwind.config.js
Labels: Request: Changes
